# -*- coding: utf-8 -*-
"""Image_PIL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_M_jEA0ZQj2Lv6E1B0Qp2qpT1d3LCI_
"""

from PIL import Image, ImageFilter

path = '/content/sample_data/conti_logo.jpg'
img = Image.open(path) 
img

print(img.format)
filtered_img = img.filter(ImageFilter.BLUR)
filtered_img.save("conti_logo_blured", 'JPEG')

filtered_img2 = img.filter(ImageFilter.SMOOTH)
filtered_img2 = img.filter(ImageFilter.SHARPEN)
filtered_img2 = img. convert('L')
filtered_img2.save("conti_logo_grey", 'JPEG')
#filtered_img2
filtered_img2

# Rotate image by angle
filtered_img3 = filtered_img2.rotate(180)
filtered_img3

# Resize the image, same image but small size
resize= filtered_img2.resize((30,30))
resize

filtered_img2.size

#crop image
box = (100,100,400,400)
cropped_img = filtered_img2.crop(box)
cropped_img

#To get small size image with same clarity
filtered_img2.thumbnail((90,90))
filtered_img2.save('new_image.jpeg')

#To get small size image with same clarity
filtered_img2.thumbnail((90,90))
filtered_img2.save('new_image.jpeg')

print("Python Image Library!!!")

